export const DISCOVER_LIST_REQUEST = 'DISCOVER_LIST_REQUEST';
export const DISCOVER_LIST_SUCCESS = 'DISCOVER_LIST_SUCCESS';
export const DISCOVER_LIST_FAILURE = 'DISCOVER_LIST_FAILURE';

export const DISCOVER_PULL_REQUEST = 'DISCOVER_PULL_REQUEST';
export const DISCOVER_PULL_SUCCESS = 'DISCOVER_PULL_SUCCESS';
export const DISCOVER_PULL_FAILURE = 'DISCOVER_PULL_FAILURE';

export const DISCOVER_DETAIL_REQUEST = 'DISCOVER_DETAIL_REQUEST';
export const DISCOVER_DETAIL_SUCCESS = 'DISCOVER_DETAIL_SUCCESS';
export const DISCOVER_DETAIL_FAILURE = 'DISCOVER_DETAIL_FAILURE';

export const DISCOVER_LIST_LOADMORE = 'DISCOVER_LIST_LOADMORE';
export const DISCOVER_LIST_CLEAR = 'DISCOVER_LIST_CLEAR';

export const VOTE_REQUEST = 'VOTE_REQUEST';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const VOTE_FAILURE = 'VOTE_FAILURE';

export const SET_DISCOVER_POST_ID = 'SET_DISCOVER_POST_ID';