// Login  
export const VIDEO_DATA_REQUEST = 'VIDEO_DATA_REQUEST';
export const VIDEO_DATA_SUCCESS = 'VIDEO_DATA_SUCCESS';
export const VIDEO_DATA_FAILURE = 'VIDEO_DATA_FAILURE';
export const VIDEO_LIST_LOADMORE = 'VIDEO_LIST_LOADMORE';

