// Login  
export const FUND_DATA_REQUEST = 'FUND_DATA_REQUEST';
export const FUND_DATA_SUCCESS = 'FUND_DATA_SUCCESS';
export const FUND_DATA_FAILURE = 'FUND_DATA_FAILURE';
export const FUND_LIST_LOADMORE = 'FUND_LIST_LOADMORE';

