// Login  
export const REPORT_REQUEST = 'REPORT_REQUEST';
export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAILURE = 'REPORT_FAILURE';

export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAILURE = 'GET_REPORT_FAILURE';

export const SET_POST_ID = 'SET_POST_ID';

export const COMMENT_REQUEST = 'COMMENT_REQUEST';
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS';
export const COMMENT_FAILURE = 'COMMENT_FAILURE';

export const REPORT_SUCCESS_PULL = 'REPORT_SUCCESS_PULL';
export const REPORT_REQUEST_PULL = 'REPORT_REQUEST_PULL';
export const REPORT_FAILURE_PULL = 'REPORT_FAILURE_PULL';
export const COMMENT_UPDATED_SUCCESS = 'COMMENT_UPDATED_SUCCESS';

export const SET_REDIRECTION = 'SET_REDIRECTION';
export const IS_REPORT_SCREEN = 'IS_REPORT_SCREEN';
