export const RECENT_REQUEST = 'RECENT_REQUEST';
export const RECENT_SUCCESS = 'RECENT_SUCCESS';
export const RECENT_FAILURE = 'RECENT_FAILURE';

export const FAV_REQUEST = 'FAV_REQUEST';
export const FAVORITE_SUCCESS = 'FAVORITE_SUCCESS';
export const FAV_SUCCESS = 'FAV_SUCCESS';
export const FAV_FAILURE = 'FAV_FAILURE';
export const RECENT_FAV_CLEAR = 'RECENT_FAV_CLEAR';

export const RECENT_PULL_TO_REFRESH_REQUEST = 'RECENT_PULL_TO_REFRESH_REQUEST';

