// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Signup step-1
export const SIGNUP_REQUEST_INTORDUCER = "SIGNUP_REQUEST_INTORDUCER";
export const SIGNUP_SUCCESS_INTORDUCER = "SIGNUP_SUCCESS_INTORDUCER";
export const SIGNUP_FAILURE_INTORDUCER = "SIGNUP_FAILURE_INTORDUCER";

// Signup step-2
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Forget Password

export const FORGET_REQUEST = "FORGET_REQUEST";
export const FORGET_SUCCESS = "FORGET_SUCCESS";
export const FORGET_FAILURE = "FORGET_FAILURE";

// Enter PIN

export const CODE_REQUEST = "CODE_REQUEST";
export const CODE_SUCCESS = "CODE_SUCCESS";
export const CODE_FAILURE = "CODE_FAILURE";

// Reset Password

export const RESET_REQUEST = "RESET_REQUEST";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILURE = "RESET_FAILURE";

//common Config

export const CATEGORY_DATA_REQUEST = "CATEGORY_DATA_REQUEST";
export const CATEGORY_DATA_SUCCESS = "CATEGORY_DATA_SUCCESS";
export const CATEGORY_DATA_FAILURE = "CATEGORY_DATA_FAILURE";

//check version
export const CHECK_VERSION_REQUEST = "CHECK_VERSION_REQUEST";
export const CHECK_VERSION_SUCCESS = "CHECK_VERSION_SUCCESS";
export const CHECK_VERSION_FAILURE = "CHECK_VERSION_FAILURE";

//set session data
export const SET_SESSION_REQUEST = "SET_SESSION_REQUEST";
export const SET_SESSION_SUCCESS = "SET_SESSION_SUCCESS";
export const SET_SESSION_FAILURE = "SET_SESSION_FAILURE";

//resend code
export const REQUEST_NEW_ONE_REQUEST = "REQUEST_NEW_ONE_REQUEST";
export const REQEUST_NEW_ONE_SUCCESS = "REQEUST_NEW_ONE_SUCCESS";
export const REQUEST_NEW_ONE_FAILURE = "REQUEST_NEW_ONE_FAILURE";

//Share Loading
export const SHAREING_REQUEST = "SHAREING_REQUEST";
export const SHAREING_SUCCESS = "SHAREING_SUCCESS";
export const SHAREING_FAILURE = "SHAREING_FAILURE";
export const SHAREING_OPEN = "SHAREING_OPEN";

export const INTERNET_STATE = "INTERNET_STATE";
