// Login
export const PRODUCT_DATA_REQUEST = 'PRODUCT_DATA_REQUEST';
export const PRODUCT_DATA_PULLTOREFESH = 'PRODUCT_DATA_PULLTOREFESH';
export const PRODUCT_DATA_SUCCESS = 'PRODUCT_DATA_SUCCESS';
export const PRODUCT_DATA_FAILURE = 'PRODUCT_DATA_FAILURE';
export const PRODUCT_LIST_LOADMORE = 'PRODUCT_LIST_LOADMORE';
export const PRODUCT_DATA_REQUEST_LOAD_MORE = 'PRODUCT_DATA_REQUEST_LOAD_MORE';
export const PRODUCT_LIST_LOADMORE_FAILURE = 'PRODUCT_LIST_LOADMORE_FAILURE';
