import LocalizedStrings from 'react-native-localization';
const language = new LocalizedStrings({
    en: {
        Vote: 'Vote',
        Voted: 'Voted',
        AssetClass: 'Asset Class ',
        InvestmentUniverse: 'Investment Universe ',
        FundFamily: 'Fund Family',
        ExitAppMessage: 'Exiting the application? ',
        Version: 'Version:',
        NOFAV: 'NO FAVORITES HAVE BEEN ADDED YET',
        NOFAVDES: 'Whenever you see this icon, tap it! Everything you favorite will be saved here.',
        RiskProfileResult: 'Based on your answers, you have an XXXXXX Risk Tolerance investment profile. Below you can see a sample investment portfolio in USD following an XXXXXX strategy.',
        TypeMessage: 'Type a message...',
        RecentContent: 'Open files in the Library and your recent items will be visible here.',
        NoFavItems: 'NO FAVORITES HAVE BEEN ADDED YET',
        FavContent: 'Whenever you see this icon, tap it! Everything you favorite will be saved here.',
        NoRecentItems: 'NO RECENT ITEMS',
        ActivateTouchIDAlert: 'Do you want to activate TouchID?',
        OK: 'OK',
        ExitApp: 'Exit App',
        ThisSurveyWillEndOn: 'This survey will end on',
        SearchInLib: 'Search in "Library"',
        Done: 'Done',
        Clear: 'Clear',
        Share: 'Share',
        Browser: 'Open in Browser',
        BrowserIOS: 'Open in Safari',
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        Print: 'Print',
        InternetConnection: "Please check your internet connection",
        NotSignInContent: 'Get exclusive content and enjoy easy fast access to all your favorite documents.',
        WhySignIn: 'Why Sign in to ITA Connect?',
        YES: 'YES',
        NO: 'NO',
        RememberAccountSettings: 'Remember your account settings on this device?',
        ChangePassword: 'Change Password',
        ITATeam: 'ITA App Team',
        me: 'ME,',
        Gallary: 'GALLERY',
        Camera: 'CAMERA',
        Close: 'CLOSE',
        ChooseImageFrom: 'Choose image from...',
        NoMessageFound: 'No messages found for this ticket.',
        SystemMessage: 'Your message has been sent, if a reply is needed, we will contact you shortly.',
        Send: 'Send',
        NotificationLanguage: 'Notification Language',
        TouchIdTradeMark: 'Touch ID is a registered trademark of Apple Inc.',
        TouchIdTurnOff: 'You can turn off Touch ID at any time from here.',
        TouchIdWarning: 'Keep in mind, if your device is lost, stolen or shared with anyone, they will have access to your accounts with saved logins and passwords. We do not recommend using Touch ID if you plan to share this device with others. ',
        TouchIdMessage: 'When you sign into your account using Touch ID, you will not need to input your password. ',
        FaceIdTradeMark: 'Face ID is a registered trademark of Apple Inc.',
        FaceIdTurnOff: 'You can turn off Face ID at any time from here.',
        FaceIdWarning: 'Keep in mind, if your device is lost, stolen or shared with anyone, they will have access to your accounts with saved logins and passwords. We do not recommend using Face ID if you plan to share this device with others. ',
        FaceIdMessage: 'When you sign into your account using Face ID, you will not need to input your password. ',
        GetStarted: 'Get Started',
        Settings: 'Settings',
        EnterClientName: 'Enter client name',
        WhoIsTheClient: 'Who is the client?',
        YourRiskToleranceProfile: 'Your risk tolerance profile',
        Bookmarked: 'Bookmarked',
        Bookmark: 'Bookmark',
        SeeAllVideos: 'See all videos',
        Password: "Password",
        Discover: "Discover",
        Evolution: "Evolution",
        Filter: "Filter",
        Flyer: "Flyers",
        FundPlatform: "Fund Platform",
        Language: "Language",
        Notification: "Notification",
        Products: "Products",
        Profile: "Profile",
        ReportAnIssue: 'REPORT AN ISSUE',
        SmallReportAnIssue: 'Report An Issue',
        RiskProfile: "Risk Profile",
        Step: 'Step',
        Security: "Security",
        SocialPosts: "Social Posts",
        TouchID: "Touch ID®",
        FaceID: "Face ID",
        Vidoes: "Videos",
        Library: "Library",
        Resource: "Resources",
        Night_mode: 'Night Mode',
        Getting_started: 'Getting Started',
        //common
        PH_EMAIL: 'Enter your Email',
        PH_NAME: 'Enter your Name',
        PH_PASSWORD: 'Enter your Password',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: 'Confirm Password',
        PH_FIRST_NAME: 'Enter your firstname',
        PH_LAST_NAME: 'Enter your lastname',
        PH_INTRODUCER_CODE: 'Enter your Introducer Code',
        //common error
        ER_VALID_EMAIL: 'Enter your valid email address',
        ER_CURRENT_PASSWORD: 'Enter your current password',
        ER_NEW_PASSWORD: 'Enter your new password',
        ER_PASSWORD_MISMATCH: 'New Password and Confirm Password do not match',
        ER_CONFIRM_PASSWORD: 'Enter your confirm password',
        ER_INTRODUCER_CODE: 'Please enter your Introducer Code',
        ER_ENTER_EMAIL: 'Please enter your email address',
        ER_SELECTED_IMAGE: 'Please select your picture',
        ER_ENTER_PASS: 'Please enter your Password',
        ER_ENTER_NAME: 'Please enter your Name',
        ER_CONFIRMATION_CODE: 'Please enter your Confirmation Code',
        ER_ENTER_CONFIRM: 'Please enter confirm your password',
        ER_PASS_NOT_MATCH: 'Password doesn\'t match',
        //SignIn
        SignIn: "Sign In",
        Signup: "Sign Up",
        RememberMe: "Remember me",
        ForgotPassword: "Forget Password?",
        ContinueAsGuest: "Continue as guest",
        Privacy: "Privacy",
        Preferences: "Preferences",
        About: "About",
        CopyRight: "© 2019 ITA Distribution. All rights reserved.",
        //change password
        Current: "Current",
        New: "New",
        Confirm: "Confirm",
        Save: "Save",
        //EnterCode
        EnterConfirmationCode: "Enter Confirmation Code",
        Enter6DigitCode: "Enter the 6-digit code we sent to your",
        RequestNewOne: "Request a new code",
        ReturnToLogin: "Return to Sign In",
        //Flyer
        SalesFlyer: "Sales Flyers",
        Adverts: "Adverts",
        Guide: "Guide",
        //forgot password
        TroubleLogin: "Trouble logging in?",
        HelpUsToIdentify: "Help us identify it's you and we'll get you back on track.",
        //Language Options
        LanguageOptions: "Language Options",
        ChineseTradition: "Chinese",
        ChineseSimplified: "Chinese Simplified",
        English: "English",
        Japanese: "Japanese",
        Korean: "Korean",
        Portugese: "Portugese",
        Russian: "Russian",
        Spanish: "Spanish",
        //Notification
        PushNotification: "Push Notification",
        NewsUpdate: "News Update",
        LibraryUpdate: "Library Update",
        //Products
        ProductInsert: "   Product Insert   ",
        ProductProfile: "   Product Profile   ",
        Funds: "   Funds   ",
        //Profile
        Recent: "Recent",
        Favorite: "Favorites",
        //Report an Issue
        ReportAnIssueConversationStart: "Conversations started in this app will be visible and listed here",
        //Reset Password
        ResetPassword: "Enter New Password",
        //Resources
        TakeTest: "TAKE TEST",
        Search: "SEARCH",
        //Risk Profile
        Continue: "CONTINUE",
        Calculate: "CALCULATE",
        //Settings
        SignOut: "Sign out",
        SignOutWarning: "Are you sure you want to sign out?",
        Cancel: "Cancel",
        Yes: "Yes",
        FAQ: "FAQ",
        //Signup Password
        TermsAndConditions: "Terms & Conditions",
        AgreeTerms: "By clicking " + '"Sign Up"' + " I agree to ITA Distribution's",
        //SocialPosts
        TipOfTheMonth: "Tip of the Month",
        ProductHighlight: "Product Hightlight",
        Quote: "Quote",
        //DiscoverList
        PrintedVersion: "PRINTED VERSION",
        DigitalOnly: "DIGITAL ONLY",
        PrintAndDigital: "PRINT AND DIGITAL",
        Submit: 'SUBMIT',
        Submited: "SUBMITED",
        //ProductList
        ViewAll: "View all",
        //Getting Started        
        Skip: "SKIP",
        WelcomeToITA: "Welcome to ITA Connect",
        WelcomeToITADetail: "A mobile app for managing business on the go, connecting you to the tools for success.",
        DiscoverDetail: "Find the latest company news, current promotions, live polls and more.",
        LibraryDetail: "Convenient access to investors and marketing materials.",
        LibraryMore: "Easily send and share files.",
        ResourceDetail: "Quick snapshot of your clients' risk profile based off individual responses.",
        ResourceMore: "Interactive fund platform with search and filter capabilities.",
        ProfileDetail: "Easily find your recent activity and bookmarked materials for quick access to the resources you use most.",
        CancelRiskProfileTest: "Are you sure you want to close the test ?",
        PasswordRules: "For security purposes, we suggest you use a strong password that is not used elsewhere. Guidelines for a strong password include:\nAt least one letter (upper or lowercase)\nAt least one number\nAt least one of these special characters: ! # $ % + / = @ ~",
        NotificationRules: "Enable notifications from ITA Connect in the Settings of your mobile device to stay up to date with the latest news and enhancements from Investors Trust’s Mobile App Team.",
        NO_DATA_FOUND: 'No data found',
        SEARCHINFUND: 'Search by ISIN or Fund Name',
        FingerprintRequired: 'Fingerprint Required',
        TouchSensor: 'Touch Sensor',
    },
    "ru": {
        Vote: 'ПРОГОЛОСОВАТЬ',
        Voted: 'ПРОГОЛОСОВАЛИ',
        AssetClass: 'Класс Активов',
        InvestmentUniverse: 'Инвестиционное Пространство',
        FundFamily: 'Семейство фондов',
        ExitAppMessage: 'Выйти из приложения?',
        Version: 'Версия',
        NOFAV: 'ИЗБРАННОЕ НЕ БЫЛО ДОБАВЛЕНО',
        NOFAVDES: 'Всякий раз, когда вы видите этот значок, коснитесь его! Все, что вам нравится, будет сохранено здесь.',
        RiskProfileResult: 'Согласно вашим ответам, ваш инвестиционный профиль толерантности к риску - XXXXXX. Ниже пример инвестиционного портфеля в USD для XXXXXX стратегии.',
        TypeMessage: 'Введите сообщение ...',
        RecentContent: 'Откройте файлы в Библиотеке и ваши недавние элементы поиска будут отображены здесь.',
        NoFavItems: 'ИЗБРАННОЕ НЕ БЫЛО ДОБАВЛЕНО',
        FavContent: 'Всякий раз, когда вы видите этот значок, коснитесь его! Все, что вам нравится, будет сохранено здесь.',
        NoRecentItems: 'НЕДАВНИЕ ЗАПРОСЫ ОТСУТСТВУЮТ',
        ActivateTouchIDAlert: 'Хотите активировать Touch ID?',
        OK: 'OK',
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        ExitApp: 'Выйти из приложения',
        ThisSurveyWillEndOn: 'Данный опрос закончится',
        SearchInLib: 'Поиск в библиотеке',
        Done: 'Готово',
        Clear: 'Очистить',
        Share: 'Поделиться',
        Browser: 'Открыть в Браузере',
        BrowserIOS: 'Открыть в Safari',
        Print: 'Распечатать',
        InternetConnection: "Пожалуйста, проверьте ваше интернет-соединение",
        NotSignInContent: 'Получите эксклюзивный контент и наслаждайтесь легким и быстрым доступом ко всем вашим любимым документам.',
        WhySignIn: 'Для чего требуется вход в ITA Connect?',
        YES: 'Да',
        NO: 'Нет',
        RememberAccountSettings: 'Запомнить настройки вашей учетной записи на этом устройстве?',
        ChangePassword: 'Изменить пароль',
        ITATeam: 'Команда Приложения ITA App',
        me: 'Я,',
        Gallary: 'ГАЛЕРЕЯ',
        Camera: 'КАМЕРА',
        Close: 'ЗАКРЫТЬ',
        ChooseImageFrom: 'Выбрать изображение из',
        NoMessageFound: 'Нет сообщений для этого тикета.',
        SystemMessage: 'Ваше сообщение было отправлено; если требуется ответ, мы свяжемся с вами в ближайшее время.',
        Send: 'Отправить',
        NotificationLanguage: 'Язык уведомлений',
        TouchIdTradeMark: 'Touch ID является зарегистрированным товарным знаком Apple Inc.',
        TouchIdTurnOff: 'Вы можете отключить Touch ID в любое время.',
        TouchIdWarning: 'Имейте в виду, если ваше устройство потеряно, украдено или передано кому-либо, третье лицо получит доступ к вашим учетным записям с сохраненными логинами и паролями. Мы не рекомендуем использовать Touch ID, если вы планируете использовать это устройство с другими людьми.',
        TouchIdMessage: 'Когда вы входите в свою учетную запись с помощью Touch ID, вам не нужно вводить пароль.',
        FaceIdTradeMark: 'Face ID iявляется зарегистрированным товарным знаком Apple Inc.',
        FaceIdTurnOff: 'Вы можете отключить Face ID в любое время.',
        FaceIdWarning: 'Имейте в виду, если ваше устройство потеряно, украдено или передано кому-либо, третье лицо получит доступ к вашим учетным записям с сохраненными логинами и паролями. Мы не рекомендуем использовать Face ID, если вы планируете использовать это устройство с другими людьми.',
        FaceIdMessage: 'Когда вы входите в свою учетную запись с помощью Face ID, вам не нужно вводить пароль.',
        GetStarted: 'Начать',
        Settings: 'Настройки',
        EnterClientName: 'Введите имя клиента',
        WhoIsTheClient: 'Кто является клиентом?',
        YourRiskToleranceProfile: 'Ваш профиль толерантности к риску',
        Bookmarked: 'Добавлено в закладки',
        Bookmark: 'Закладка',
        SeeAllVideos: 'Просмотр всех видео',
        Password: "Пароль",
        Discover: "Новости",
        Filter: "Фильтр",
        Flyer: "Флаеры",
        FundPlatform: "Платформа Фондов",
        Language: "Язык",
        Notification: "Оповещения",
        Products: "Продукты",
        Profile: "Профиль",
        ReportAnIssue: 'СООБЩИТЬ О ПРОБЛЕМЕ',
        SmallReportAnIssue: 'Сообщить о проблеме',
        RiskProfile: "Рисковый Профиль",
        Step: 'Шаг',
        Security: "Безопасность",
        SocialPosts: "Публикации в соц.сетях",
        TouchID: "Touch ID®",
        FaceID: "Face ID",
        Vidoes: "Видео",
        Library: "Библиотека",
        Resource: "Ресурсы",
        Night_mode: 'Ночной режим',
        Getting_started: 'Начать',
        //common
        PH_EMAIL: 'Введите адрес электронной почты',
        PH_NAME: 'Введите ваше имя',
        PH_PASSWORD: 'Введите ваш пароль',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: 'Подтвердите Пароль',
        PH_FIRST_NAME: 'Введите свое имя',
        PH_LAST_NAME: 'Введите свою фамилию',
        PH_INTRODUCER_CODE: 'Введите свой код представителя',
        //common error
        ER_VALID_EMAIL: 'Введите свой действующий адрес электронной почты',
        ER_CURRENT_PASSWORD: 'Введите ваш текущий пароль',
        ER_NEW_PASSWORD: 'Введите ваш новый пароль',
        ER_PASSWORD_MISMATCH: 'Новый пароль и подтверждение пароля не совпадают',
        ER_CONFIRM_PASSWORD: 'Введите ваш пароль для подтверждения',
        ER_INTRODUCER_CODE: 'Пожалуйста, введите ваш код представителя',
        ER_ENTER_EMAIL: 'Пожалуйста, введите свой адрес электронной почты',
        ER_SELECTED_IMAGE: 'Пожалуйста, выберите вашу фотографию',
        ER_ENTER_PASS: 'Пожалуйста, введите пароль',
        ER_ENTER_NAME: 'Пожалуйста, введите ваше имя',
        ER_CONFIRMATION_CODE: 'Пожалуйста, введите ваш код подтверждения',
        ER_ENTER_CONFIRM: 'Пожалуйста, подтвердите ваш пароль',
        ER_PASS_NOT_MATCH: 'Пароль не подходит',
        //SignIn
        SignIn: "Войти в систему",
        Signup: "Зарегистрироваться",
        RememberMe: "Запомнить меня",
        ForgotPassword: "Забыли пароль?",
        ContinueAsGuest: "Продолжить как гость",
        Privacy: "Конфиденциальность",
        Preferences: "Предпочтения",
        About: "Информация",
        CopyRight: "© 2019 ITA Distribution. Все права защищены. Версия 1.0",
        //change password
        Current: "Текущий",
        New: "Новый",
        Confirm: "Подтвердить",
        Save: "Сохранить",
        //EnterCode
        EnterConfirmationCode: "Введите код подтверждения",
        Enter6DigitCode: "Введите 6-значный код, который мы отправили на ваш xxxx@xxxxxxxxx.com.",
        RequestNewOne: "Запросить новый код",
        ReturnToLogin: "Вернуться к входу",

        //forgot password
        TroubleLogin: "Проблемы при входе в систему?",
        HelpUsToIdentify: "Помогите нам определить, что это вы, и мы поможем.",
        //Language Options
        LanguageOptions: "Варианты языка",
        ChineseTradition: "中文",
        ChineseSimplified: "简体中文",
        English: "English",
        Japanese: "日本語",
        Korean: "한국어",
        Portugese: "Português",
        Russian: "Русский",
        Spanish: "Español",
        //Notification
        PushNotification: "Push-Уведомления",
        NewsUpdate: "Обновление новостей",
        LibraryUpdate: "Обновление библиотеки",
        //Profile
        Recent: "Недавнее",
        Favorite: "Избранное",
        //Report an Issue
        ReportAnIssueConversationStart: "Диалоги, проводимые в этом приложении, будут видны и перечислены здесь",
        //Reset Password
        ResetPassword: "Введите новый пароль",
        //Resources
        TakeTest: "Пройти тест",
        Search: "Поиск",
        //Risk Profile
        Continue: "Продолжить",
        Calculate: "Рассчитать",
        //Settings
        SignOut: "Выйти из системы",
        SignOutWarning: "Вы уверены, что хотите выйти?",
        Cancel: "Отмена",
        Yes: "Да",
        FAQ: "Часто задаваемые вопросы",
        //Signup Password
        TermsAndConditions: "Условия",
        AgreeTerms: "Кликнув " + '"Зарегистрироваться"' + " Я согласен с ITA Group",

        //DiscoverList
        PrintedVersion: "PRINTED VERSION",
        DigitalOnly: "DIGITAL ONLY",
        PrintAndDigital: "PRINT AND DIGITAL",
        Submit: 'Отправить',
        Submited: "Отправлено",
        //ProductList
        ViewAll: "Посмотреть все",
        //Getting Started
        Skip: "Пропустить",
        WelcomeToITA: "Добро пожаловать в ITA Connect",
        WelcomeToITADetail: "Мобильное приложение для управления бизнесом, находясь в движении, которое объединяет вас с инструментами для достижения успеха.",
        DiscoverDetail: "Найти последние новости компании, текущие промоакции, live-опросы и многое другое",
        LibraryDetail: "Удобный доступ к ресурсам и маркетинговым материалам Investors Trust",
        LibraryMore: "Легко сохраняйте файлы и делитесь файлами",
        ResourceDetail: "Резюме профиля риска ваших клиентов на основе индивидуальных ответов",
        ResourceMore: "Интерактивная платформа фондов с возможностями поиска и фильтрации",
        ProfileDetail: "Вы можете легко отследить свои недавние действия и сохраненные материалы для быстрого доступа к наиболее часто используемым ресурсам.",
        CancelRiskProfileTest: "Вы уверены, что хотите закрыть тест?",
        PasswordRules: "В целях безопасности мы рекомендуем использовать надежный пароль, который не используется в других местах. Рекомендации по созданию надежного пароля включают в себя:\nКак минимум одна буква (заглавная или строчная)\nКак минимум одна цифра\nКак минимум один специальный символ ! # $ % + / = @ ~",
        NotificationRules: 'Включите уведомления от ITA Connect в Настройках вашего мобильного устройства, чтобы быть в курсе последних новостей и улучшений от Команды Мобильного Приложения Investors Trust.',
        NO_DATA_FOUND: 'Данные не найдены',
        SEARCHINFUND: 'Поиск по ISIN или названию фонда',
        FingerprintRequired: 'Требуется отпечаток пальца',
        TouchSensor: 'Сенсор касания',
    },
    "zh-hant": {
        Vote: '投票',
        Voted: '您已投票',
        AssetClass: '資產類別',
        InvestmentUniverse: "投資類別",
        FundFamily: "資產經理",
        ExitAppMessage: '確認退出應用程式?',
        Version: '版本：',
        NOFAV: '尚未有收藏文件',
        NOFAVDES: '您可以點選此圖標將喜歡的文件存至收藏夾!',
        RiskProfileResult: '根據您所選擇的答案，您的投資風險承受能力較高。以下為採用XXXXXX策略的美元投資組合樣本。',
        TypeMessage: '輸入訊息…',
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        RecentContent: '於此處查看最近的閱讀記錄和已存取的資料。',
        NoFavItems: '尚未有收藏文件',
        FavContent: '您可以點選此圖標將喜歡的文件存至收藏夾!',
        NoRecentItems: '沒有閱讀紀錄',
        ActivateTouchIDAlert: '你想開啟指紋識別Touch ID嗎？',
        OK: '確定',
        ExitApp: '退出應用程式',
        ThisSurveyWillEndOn: '問卷結束日期',
        SearchInLib: '在資料庫搜尋',
        Done: '完成',
        Clear: '清除',
        Share: '分享',
        Browser: '在瀏覽器中打開',
        BrowserIOS: '在Safari中打開',
        Print: '列印',
        InternetConnection: "請檢查您的互聯網連接",
        NotSignInContent: '獲取獨家內容，並輕鬆快速地查看所有喜歡的文檔。',
        WhySignIn: '為什麼登錄ITA Connect？',
        YES: '是',
        NO: '否',
        RememberAccountSettings: '在此應用程式上保存帳戶設置嗎？',
        ChangePassword: '更改密碼',
        ITATeam: 'ITA App團隊',
        me: '我',
        Gallary: '相片庫',
        Camera: '相機',
        Close: '關閉',
        ChooseImageFrom: '選擇圖檔',
        NoMessageFound: '沒有可用信息',
        SystemMessage: '您的信息已發送，如需要回覆，我們會盡快與您聯繫。',
        Send: '發送',
        NotificationLanguage: '通知語言',
        TouchIdTradeMark: '指紋識別 Touch ID是Apple Inc. 的註冊商標。',
        TouchIdTurnOff: '您可以從此處關閉指紋識別 Touch ID功能。',
        TouchIdWarning: '請注意，如果您的手機遺失，被竊或與其他人共同使用，他們將可以使用已保存的資訊和密碼登錄您的帳戶。如果您不是唯一使用此手機者，我們建議您不要使用指紋識別 Touch ID。',
        TouchIdMessage: '使用指紋識別 Touch ID登錄帳戶時，無需輸入密碼。',
        FaceIdTradeMark: '指紋識別 Face ID是Apple Inc. 的註冊商標。',
        FaceIdTurnOff: '您可以從此處關閉指紋識別 Face ID功能。',
        FaceIdWarning: '請注意，如果您的手機遺失，被竊或與其他人共同使用，他們將可以使用已保存的資訊和密碼登錄您的帳戶。如果您不是唯一使用此手機者，我們建議您不要使用指紋識別 Face ID。',
        FaceIdMessage: '使用指紋識別 Face ID登錄帳戶時，無需輸入密碼。',
        GetStarted: '開始',
        Settings: '設定',
        EnterClientName: '請輸入客戶姓名',
        WhoIsTheClient: '誰是客戶？',
        YourRiskToleranceProfile: '您的投資風險承受能力',
        Bookmarked: '已加入書籤',
        Bookmark: '書籤',
        SeeAllVideos: '觀賞所有影片',
        Password: "密碼",
        Discover: "探索",

        Filter: "篩選",
        Flyer: "文宣",
        FundPlatform: "基金平台",
        Language: "語言",
        Notification: "通知",
        Products: "產品",
        Profile: "帳戶資料",
        ReportAnIssue: '報告問題',
        SmallReportAnIssue: '報告問題',
        RiskProfile: "投資風險評估",
        Step: '步驟',
        Security: "安全性",
        SocialPosts: "社群文章",
        TouchID: "指紋識別 Touch ID®",
        FaceID: "臉部辨識",
        Vidoes: "影片",
        Library: "資料庫",
        Resource: "資源工具",
        Night_mode: '夜间模式',
        Getting_started: '準備開始',
        //common
        PH_EMAIL: '輸入您的電子郵箱',
        PH_NAME: '輸入您的名字',
        PH_PASSWORD: '輸入您的密碼',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: '確認密碼',
        PH_FIRST_NAME: '輸入您的名字',
        PH_LAST_NAME: '輸入您的姓氏',
        PH_INTRODUCER_CODE: '輸入您的介紹人號碼',
        //common error
        ER_VALID_EMAIL: '請輸入您的有效電子郵件地址',
        ER_CURRENT_PASSWORD: '輸入目前密碼',
        ER_NEW_PASSWORD: '輸入新密碼',
        ER_PASSWORD_MISMATCH: '新密碼和確認密碼不符',
        ER_CONFIRM_PASSWORD: '輸入確認密碼',
        ER_INTRODUCER_CODE: '請輸入您的介紹人號碼',
        ER_ENTER_EMAIL: '請輸入您的電子郵件地址',
        ER_SELECTED_IMAGE: '請選擇您的照片',
        ER_ENTER_PASS: '請輸入您的密碼',
        ER_ENTER_NAME: '請輸入您的名字',
        ER_CONFIRMATION_CODE: '請輸入您的確認碼',
        ER_ENTER_CONFIRM: '請確認您的密碼',
        ER_PASS_NOT_MATCH: '密碼不相符',
        //SignIn
        SignIn: "登入",
        Signup: "註冊",
        RememberMe: "記住帳號",
        ForgotPassword: "忘記密碼？",
        ContinueAsGuest: "以訪客身份瀏覽",
        Privacy: "隱私",
        Preferences: "偏好",
        About: "關於",
        CopyRight: "© 2019 ITA Distribution. All rights reserved.",
        //change password
        Current: "現有密碼",
        New: "新密碼",
        Confirm: "確認密碼",
        Save: "保存",
        //EnterCode
        EnterConfirmationCode: "輸入確認碼",
        Enter6DigitCode: "輸入我們發送至 xxxx@xxxxxxxxx.com 的6位數確認碼",
        RequestNewOne: "重發確認碼",
        ReturnToLogin: "返回登錄",

        //forgot password
        TroubleLogin: "登錄時遇到問題？",
        HelpUsToIdentify: "請協助我們識別是你本人，我們會引導你完成登錄。",
        //Language Options
        LanguageOptions: "語言選項",
        ChineseTradition: "中文",
        ChineseSimplified: "简体中文",
        English: "English",
        Japanese: "日本語",
        Korean: "한국어",
        Portugese: "Português",
        Russian: "Русский",
        Spanish: "Español",
        //Notification
        PushNotification: "推送通知",
        NewsUpdate: "新聞動態",
        LibraryUpdate: "資料庫更新",
        //Profile
        Recent: "閱讀紀錄",
        Favorite: "收藏文件",
        //Report an Issue
        ReportAnIssueConversationStart: "您所報告的問題將會列於此處",
        //Reset Password
        ResetPassword: "輸入新密碼",
        //Resources
        TakeTest: "進行測試",
        Search: "搜尋",
        //Risk Profile
        Continue: "繼續",
        Calculate: "計算",
        //Settings
        SignOut: "登出",
        SignOutWarning: "您確定要退出嗎？",
        Cancel: "取消",
        Yes: "是",
        FAQ: "常見問題",
        //Signup Password
        TermsAndConditions: "條款與細則",
        AgreeTerms: "點擊 " + '"註冊"' + " 即表示我同意ITA Distribution的條款與細則",

        //DiscoverList
        Submit: '提交',
        Submited: "已提交",
        //ProductList
        ViewAll: "查看全部",
        //Getting Started
        Skip: "略過",
        WelcomeToITA: "歡迎來到 ITA Connect",
        WelcomeToITADetail: "讓您一機在手，隨時隨地為客戶提供無懈可擊的服務。",
        DiscoverDetail: "查看公司新聞、介紹人活動、以及實時投票結果等實用功能。",
        LibraryDetail: "方便查看 Investors Trust 的實用資源和市場推廣文宣",
        LibraryMore: "輕鬆存取和分享文件",
        ResourceDetail: "根據測試結果快速了解客戶的風險承擔程度",
        ResourceMore: "具有搜尋和篩選功能的互動基金平台",
        ProfileDetail: "查看最近的閱讀記錄和已存取的資料，方便您迅速取得常用資源",
        CancelRiskProfileTest: "您確定要結束測試嗎？",
        PasswordRules: "基於安全考量，我們建議您採用未在其他平台使用過的強化密碼。密碼需包含:\n至少一個字母（大寫或小寫）\n至少一個數字\n至少一個特殊符號 ! # $ % + / = @ ~",
        NotificationRules: "設定手機開啟 ITA Connect 的通知功能，即時了解Investors Trust的最新資訊。",
        NO_DATA_FOUND: '沒有可用數據',
        SEARCHINFUND: '輸入 ISIN 或基金名稱搜尋',
        FingerprintRequired: '指紋',
        TouchSensor: '指紋感應器',
    },
    "ja": {
        Vote: '投票する',
        Voted: '投票しました',
        AssetClass: "アセットクラス",
        InvestmentUniverse: "投資地域",
        FundFamily: 'ファンド運用会社',
        ExitAppMessage: 'アプリを終了してよろしいですか？',
        Version: 'バージョン：',
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        NOFAV: '登録された項目はありません',
        NOFAVDES: 'このアイコンが表示されましたらタップしてください。こちらにお気に入りとして登録されます。',
        RiskProfileResult: 'あなたのリスク許容度は、積極的なレベルです。米ドル建てXXXXXX戦略ポートフォリオの例は以下の通りです。',
        TypeMessage: 'メッセージを入力',
        RecentContent: 'ライブラリーの書類や最近利用した項目は、こちらからご確認いただけます。',
        NoFavItems: '登録された項目はありません',
        FavContent: 'このアイコンが表示されましたらタップしてください。こちらにお気に入りとして登録されます。',
        NoRecentItems: '最近の履歴はありません',
        ActivateTouchIDAlert: 'Touch IDを有効にしてください',
        OK: 'OK',
        ExitApp: 'アプリを終了する',
        ThisSurveyWillEndOn: 'アンケート終了日',
        SearchInLib: 'ライブラリで検索する',
        Done: '完了',
        Clear: 'クリア',
        Share: 'シェア',
        Browser: 'ブラウザーで開く',
        BrowserIOS: 'Safariで開く',
        Print: '印刷',
        InternetConnection: "インターネット接続環境を確認してください",
        NotSignInContent: '情報やドキュメントに簡単かつ迅速にアクセスができます',
        WhySignIn: 'ITA Connectの利点',
        YES: 'はい',
        NO: 'いいえ',
        RememberAccountSettings: 'このデバイス上でアカウント情報を保存しますか？',
        ChangePassword: 'パスワード変更',
        ITATeam: 'ITA App Team',
        me: '私',
        Gallary: 'ギャラリー',
        Camera: 'カメラ',
        Close: '閉じる',
        ChooseImageFrom: '画像選択',
        NoMessageFound: 'このチケットに該当するメッセージはありません',
        SystemMessage: 'メッセージが送信されました。必要な場合は、順次ご返信いたします。',
        Send: '送信',
        NotificationLanguage: '希望言語',
        TouchIdTradeMark: 'Touch IDは、アップル社の登録商標です。',
        TouchIdTurnOff: 'Touch IDは、こちらからいつでも無効にすることができます。',
        TouchIdWarning: 'ログイン情報やパスワードが保存されている場合には、デバイスの紛失や、盗難にあった場合又は他人との共有の際には、アカウントへアクセスされる可能性があります。デバイスを共有する場合には、Touch IDを利用することはお勧めしません。',
        TouchIdMessage: 'からサインインする場合、パスワードが不要になります',
        FaceIdTradeMark: 'Face IDは、アップル社の登録商標です。',
        FaceIdTurnOff: 'Face IDは、こちらからいつでも無効にすることができます。',
        FaceIdWarning: 'ログイン情報やパスワードが保存されている場合には、デバイスの紛失や、盗難にあった場合又は他人との共有の際には、アカウントへアクセスされる可能性があります。デバイスを共有する場合には、Face IDを利用することはお勧めしません。',
        FaceIdMessage: 'からサインインする場合、パスワードが不要になります',
        GetStarted: '利用を開始する',
        Settings: '設定',
        EnterClientName: 'クライアントの氏名を入力してください',
        WhoIsTheClient: 'クライアント名',
        YourRiskToleranceProfile: 'リスク許容度プロファイル',
        Bookmarked: 'ブックマークが保存されました',
        Bookmark: 'ブックマーク',
        SeeAllVideos: 'ビデオ視聴',
        Password: "パスワード",
        Discover: "各種情報",

        Filter: "フィルタ",
        Flyer: "フライヤー",
        FundPlatform: "ファンドプラットフォーム",
        Language: "言語",
        Notification: "お知らせ通知",
        Products: "商品",
        Profile: "プロファイル",
        ReportAnIssue: '問題を報告する',
        SmallReportAnIssue: '問題を報告する',
        RiskProfile: "リスクプロファイル",
        Step: 'ステップ',
        Security: "セキュリティ",
        SocialPosts: "ソーシャル",
        TouchID: "タッチID",
        FaceID: "Face ID",
        Vidoes: "ビデオ",
        Library: "ライブラリ",
        Resource: "リソース",
        Night_mode: 'ナイトモード',
        Getting_started: 'アプリの内容',
        //common
        PH_EMAIL: 'メールアドレスを入力',
        PH_NAME: '氏名を入力',
        PH_PASSWORD: 'パスワードを入力',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: 'パスワード確認',
        PH_FIRST_NAME: '名を入力',
        PH_LAST_NAME: '姓を入力',
        PH_INTRODUCER_CODE: 'イントロデューサーコードを入力してください',
        //common error
        ER_VALID_EMAIL: '有効なメールアドレスを入力してください',
        ER_CURRENT_PASSWORD: '現在のパスワード',
        ER_NEW_PASSWORD: '新しいパスワード',
        ER_PASSWORD_MISMATCH: '新しいパスワードと確認パスワードが合致しません。',
        ER_CONFIRM_PASSWORD: 'パスワード確認',
        ER_INTRODUCER_CODE: 'イントロデューサーコードを入力してください',
        ER_ENTER_EMAIL: 'メールアドレスを入力してください',
        ER_SELECTED_IMAGE: '写真を選択してください',
        ER_ENTER_PASS: 'パスワードを入力してください',
        ER_ENTER_NAME: '氏名を入力してください',
        ER_CONFIRMATION_CODE: '認証コードを入力してください',
        ER_ENTER_CONFIRM: 'パスワードを確認してください',
        ER_PASS_NOT_MATCH: 'パスワードが合致しません',
        //SignIn
        SignIn: "サインイン",
        Signup: "新規登録",
        RememberMe: "記憶する",
        ForgotPassword: "パスワードを忘れましたか？",
        ContinueAsGuest: "ゲストとして継続する",
        Privacy: "個人情報取扱方針",
        Preferences: "一般",
        About: "アプリについて",
        CopyRight: "© 2019 ITA Distribution. All rights reserved.",
        //change password
        Current: "現在のパスワード",
        New: "新規パスワード",
        Confirm: "パスワード確認",
        Save: "保存",
        //EnterCode
        EnterConfirmationCode: "認証コードを入力してください",
        Enter6DigitCode: "xxxx@xxxxxxxxx.comへ送信された6桁のコードを入力してください",
        RequestNewOne: "新しいコードをリクエストする",
        ReturnToLogin: "サインイン画面へ戻る",

        //forgot password
        TroubleLogin: "ログインできませんか？",
        HelpUsToIdentify: "ご本人確認をします",
        //Language Options
        LanguageOptions: "言語選択",
        ChineseTradition: "中文",
        ChineseSimplified: "简体中文",
        English: "English",
        Japanese: "日本語",
        Korean: "한국어",
        Portugese: "Português",
        Russian: "Русский",
        Spanish: "Español",
        //Notification
        PushNotification: "プッシュ通知",
        NewsUpdate: "最新ニュース",
        LibraryUpdate: "ライブラリ更新",
        //Profile
        Recent: "履歴",
        Favorite: "お気に入り",
        //Report an Issue
        ReportAnIssueConversationStart: "アプリ上で報告された問題は、こちらに表示されます",
        //Reset Password
        ResetPassword: "新しいパスワードの入力",
        //Resources
        TakeTest: "診断する",
        Search: "検索",
        //Risk Profile
        Continue: "続ける",
        Calculate: "診断する",
        //Settings
        SignOut: "サインアウト",
        SignOutWarning: "サインアウトしてよろしいですか？",
        Cancel: "キャンセル",
        Yes: "はい",
        FAQ: "FAQ",
        //Signup Password
        TermsAndConditions: "規約及び条件",
        AgreeTerms: "”サインアップ”をクリックすることで、 " + '"サインアップ"' + " ITAグループのTerms & Conditionを承諾したこととみなします。",

        //DiscoverList
        PrintedVersion: "PRINTED VERSION",
        DigitalOnly: "DIGITAL ONLY",
        PrintAndDigital: "PRINT AND DIGITAL",
        Submit: '送信',
        Submited: "送信完了",
        //ProductList
        ViewAll: "全てを閲覧する",
        //Getting Started
        Skip: "スキップ",
        WelcomeToITA: "ITA Connectへようこそ",
        WelcomeToITADetail: "このモバイルアプリは、ご移動中でのビジネス管理を可能にします",
        DiscoverDetail: "会社最新情報、最新プロモーションその他情報はこちらからご覧いただけます",
        LibraryDetail: "インベスターズトラストのリソースや資料等は、こちらからアクセス可能です",
        LibraryMore: "簡単な操作で保存や共有ができます",
        ResourceDetail: "リスクプロファイル診断結果はこちらからご覧いただけます",
        ResourceMore: "フィルター機能付きインタラクティブな検索ツールをご利用ください",
        ProfileDetail: "最近アクセスした項目と保存されたリソースを表示します",
        CancelRiskProfileTest: "診断を終了してよろしいですか？",
        PasswordRules: "セキュリティ強化のため、これまで利用のないパスワードの利用をお勧めします。パスワードは以下を含めてください:\n最低一文字（大文字又は小文字）\n最低一つの数字・最低一つの記号 ! # $ % + / = @ ~",
        NotificationRules: "インベスターズトラストのモバイルアプリチームより、ITA Connectの最新情報や更新情報に関する通知を受取る設定ができます。",
        NO_DATA_FOUND: 'データが見つかりません',
        SEARCHINFUND: 'ISIN又はファンド名称による検索',
        FingerprintRequired: '指紋認証をしてください',
        TouchSensor: 'タッチセンサー',
    },
    "ko": {
        Vote: '투표',
        Voted: '투표 완성',
        AssetClass: "자산 클래스",
        InvestmentUniverse: "투자 지역",
        FundFamily: "자산 운용사",
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        ExitAppMessage: '앱 나가기',
        Version: '버전:',
        NOFAV: '관심 아이템이 없습니다',
        NOFAVDES: '아이콘을 클릭하세요! 당신의 관심 아이템은 여기에 저장됩니다.',
        RiskProfileResult: '테스트 결과 당신은 공격투자형 투자자로 판정되었습니다. 당신의 투자성향에 따른 XXXXXX 투자 전략의 미화 투자 포트폴리오를 참고하세요.',
        TypeMessage: '메시지를 입력해 주세요',
        RecentContent: '최근 열람한 아이템을 찾아보실 수 있습니다.',
        NoFavItems: '관심 아이템이 없습니다',
        FavContent: '아이콘을 클릭하세요! 당신의 관심 아이템은 여기에 저장됩니다.',
        NoRecentItems: '최근 파일이 없습니다',
        ActivateTouchIDAlert: 'Touch ID를 활성화 하시겠습니까?',
        OK: 'OK',
        ExitApp: '앱 나가기',
        ThisSurveyWillEndOn: '조사 종료일 ',
        SearchInLib: '라이브러리에서 검색하기',
        Done: '클리어',
        Clear: '완성',
        Share: '공유',
        Browser: '브라우저에서 열기',
        BrowserIOS: 'Safari에서 열기',
        Print: '프린트',
        InternetConnection: "인터넷 연결을 확인하세요",
        NotSignInContent: '독보적인 콘텐츠와 즐겨찾는 문서를 빠르고 손쉽게 찾아보세요.',
        WhySignIn: 'ITA Connect에 등록한 원인은 무엇입니까?',
        YES: '네',
        NO: '아니오',
        RememberAccountSettings: '당신의 계좌 정보를 본 기기에 저장하시겠습니까?',
        ChangePassword: '비밀번호 변경',
        ITATeam: 'ITA 어플 팀',
        me: '나',
        Gallary: '갤러리',
        Camera: '카메라',
        Close: '닫기',
        ChooseImageFrom: '다음에서 이미지 선택',
        NoMessageFound: '티켓에 해당하는 메시지가 없습니다.',
        SystemMessage: '귀하의 메시지가 전송되었습니다. 필요시 빠른 시일내에 연락드리겠습니다.',
        Send: '전송',
        NotificationLanguage: '통보 언어',
        TouchIdTradeMark: 'Touch ID는 Apple Inc.의 등록상표입니다',
        TouchIdTurnOff: '지금 바로 Touch ID를 비활성화 하실 수 있습니다.',
        TouchIdWarning: '기기 분실 또는 절도가 발생했거나 타인과 공유한적이 있으시다면 본인이 아닌 제3자가 이미 저장된 아이디와 비밀번호로 계정에 접속할 수 있습니다. 만약 타인과 한개의 기기를 공유하고 계시다면 Touch ID사용은 권장드리지 않습니다.',
        TouchIdMessage: 'Touch ID를 사용하여 로그인 하실 경우, 따로 비밀번호를 입력하실 필요가 없습니다.',
        FaceIdTradeMark: 'Face ID는 Apple Inc.의 등록상표입니다',
        FaceIdTurnOff: '지금 바로 Face ID를 비활성화 하실 수 있습니다.',
        FaceIdWarning: '기기 분실 또는 절도가 발생했거나 타인과 공유한적이 있으시다면 본인이 아닌 제3자가 이미 저장된 아이디와 비밀번호로 계정에 접속할 수 있습니다. 만약 타인과 한개의 기기를 공유하고 계시다면 Face ID사용은 권장드리지 않습니다.',
        FaceIdMessage: 'Face ID를 사용하여 로그인 하실 경우, 따로 비밀번호를 입력하실 필요가 없습니다.',
        GetStarted: '시작하세요',
        Settings: '설정',
        EnterClientName: '클라이언트 성명 입력',
        WhoIsTheClient: '클라이언트 정보',
        YourRiskToleranceProfile: '당신의 투자 성향 프로파일',
        Bookmarked: '즐겨찾기 추가',
        Bookmark: '즐겨찾기',
        SeeAllVideos: '모든 동영상 보기',
        Password: "비밀번호",
        Discover: "최신 정보",

        Filter: "필터",
        Flyer: "안내전단",
        FundPlatform: "펀드 플랫폼",
        Language: "언어",
        Notification: "알림",
        Products: "상품",
        Profile: "프로파일",
        ReportAnIssue: '오류 보고',
        SmallReportAnIssue: '오류 보고',
        RiskProfile: "리스크 프로파일",
        Step: 'Step',
        Security: "보안",
        SocialPosts: "소셜 게시물",
        TouchID: "Touch ID®",
        FaceID: "Face ID",
        Vidoes: "비디오",
        Library: "라이브러리",
        Resource: "Resources",
        Night_mode: '야간모드',
        Getting_started: '사용 안내',
        //common
        PH_EMAIL: '이메일 입력',
        PH_NAME: '이름 입력',
        PH_PASSWORD: '비밀번호 입력',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: '비밀번호 확인',
        PH_FIRST_NAME: '명',
        PH_LAST_NAME: '성',
        PH_INTRODUCER_CODE: '소개자 코드 입력',
        //common error
        ER_VALID_EMAIL: '정확한 이메일 주소를 입력하세요',
        ER_CURRENT_PASSWORD: '비밀번호를 입력하세요',
        ER_NEW_PASSWORD: '새 비밀번호를 입력하세요',
        ER_PASSWORD_MISMATCH: '새 비밀번호와 재입력한 비밀번호가 일치하지 않습니다',
        ER_CONFIRM_PASSWORD: '새 비밀번호를 확인해 주세요',
        ER_INTRODUCER_CODE: '소개자 코드를 입력하세요',
        ER_ENTER_EMAIL: '이메일 주소를 입력하세요',
        ER_SELECTED_IMAGE: '사진을 선택하세요',
        ER_ENTER_PASS: '비밀번호를 입력하세요',
        ER_ENTER_NAME: '이름을 입력하세요',
        ER_CONFIRMATION_CODE: '인증 코드를 입력하세요',
        ER_ENTER_CONFIRM: '비밀번호를 확인하세요',
        ER_PASS_NOT_MATCH: '비밀번호가 일치하지 않습니다',
        //SignIn
        SignIn: "로그인",
        Signup: "등록",
        RememberMe: "로그인 정보 기억하기",
        ForgotPassword: "비밀번호 찾기",
        ContinueAsGuest: "게스트로 계속하기",
        Privacy: "개인 정보 보호",
        Preferences: "개인 설정",
        About: "About",
        CopyRight: "© 2019 ITA Distribution. All rights reserved.",
        //change password
        Current: "현재 비밀번호",
        New: "새 비밀번호",
        Confirm: "확인",
        Save: "저장",
        //EnterCode
        EnterConfirmationCode: "인증 코드 입력",
        Enter6DigitCode: "xxxx@xxxxxxxxx.com로 보내드린 6자리 코드를 입력하세요",
        RequestNewOne: "코드 재발송",
        ReturnToLogin: "로그인 페이지",

        //forgot password
        TroubleLogin: "로그인 오류 고객 지원",
        HelpUsToIdentify: "귀하의 신분을 확인할 수 있도록 협조하시기 바랍니다.",
        //Language Options
        LanguageOptions: "언어 옵션",
        ChineseTradition: "繁體中文",
        ChineseSimplified: "简体中文",
        English: "English",
        Japanese: "日本語",
        Korean: "한국어",
        Portugese: "Português",
        Russian: "Русский",
        Spanish: "Español",
        //Notification
        PushNotification: "알림",
        NewsUpdate: "뉴스 업데이트",
        LibraryUpdate: "도서관 업데이트",
        //Profile
        Recent: "최근 열람",
        Favorite: "Favorite",
        //Report an Issue
        ReportAnIssueConversationStart: "어플리케이션에서의 대화는 여기에서 찾아보세요",
        //Reset Password
        ResetPassword: "비밀번호 입력",
        //Resources
        TakeTest: "투자성형 진단하기",
        Search: "검색",
        //Risk Profile
        Continue: "CONTINUE",
        Calculate: "계산",
        //Settings
        SignOut: "로그아웃",
        SignOutWarning: "로그아웃 하시겠습니까?",
        Cancel: "취소",
        Yes: "네",
        FAQ: "FAQ",
        //Signup Password
        TermsAndConditions: "약관 & 조항",
        AgreeTerms: "클릭하세요 " + '"등록"' + " 본인은 ITA그룹의 ",

        //DiscoverList
        PrintedVersion: "PRINTED VERSION",
        DigitalOnly: "DIGITAL ONLY",
        PrintAndDigital: "PRINT AND DIGITAL",
        Submit: '제출',
        Submited: "제출 완료",
        //ProductList
        ViewAll: "전체 보기",
        //Getting Started
        Skip: "SKIP",
        WelcomeToITA: "ITA Connect에 오신걸 환영합니다",
        WelcomeToITADetail: "언제 어디서나 비지니스 관리가 가능한 모바일 어플리케이션, 당신을 성공으로 이어주는 도구",
        DiscoverDetail: "최신 회사 뉴스, 현재 프로모션, 실시간 조사보고 등을 비롯한 다양한 내용을 찾아보세요",
        LibraryDetail: "Investors Trust의 자원과 마케팅 자료에 쉽게 접근",
        LibraryMore: "손쉬운 파일의 저장 및 공유 ",
        ResourceDetail: "개인 반응을 기반으로 한 리스크 프로파일 스냅샷",
        ResourceMore: "검색 및 필터 기능을 첨가한 역동적인 펀드 플랫폼",
        ProfileDetail: "최근의 활동 및 저장 기록을 검색하여 원하는 자원에 빠르게 접속하세요",
        CancelRiskProfileTest: "테스트를 종료하시겠습니까?",
        PasswordRules: "모바일 기기 설정에서 ITA Connect앱의 알림 기능을 활성화하여 Investors Trust 모바일 어플 팀에서 전송하는 최신 업데이트를 받아보세요. \n최소 한개의 문자 (대문자 또는 소문자) 포함\n최소 한개의 숫자 포함\n최소 한개의 특수 부호 ! # $ % + / = @ ~",
        NotificationRules: "모바일 기기 설정에서 ITA Connect앱의 알림 기능을 활성화하여 Investors Trust 모바일 어플 팀에서 전송하는 최신 업데이트를 받아보세요.",
        NO_DATA_FOUND: '기록을 찾을 수 없습니다',
        SEARCHINFUND: 'ISIN 혹은 펀드 이름으로 검색하기',
        FingerprintRequired: '지문',
        TouchSensor: 'Touch Sensor',
    },
    "pt-pt": {
        Vote: 'VOTAR',
        Voted: 'VOTOU',
        AssetClass: "Classe de Ativos",
        InvestmentUniverse: "Universo de Investimento",
        FundFamily: 'Família dos Fundos',
        ExitAppMessage: 'Deseja sair do aplicativo?',
        Version: 'Versão:',
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        NOFAV: 'NENHUM FAVORITO FOI ADICIONADO',
        NOFAVDES: 'Sempre que você ver este ícone, clique nele! Tudo o que você adicionou em Favoritos será salvo aqui.',
        RiskProfileResult: 'Baseado nas suas respostas, o seu perfil de Tolerância ao Risco é XXXXXX. Segue abaixo um exemplo de um portfólio de investimento em USD, seguindo uma estratégia XXXXXX.',
        TypeMessage: 'Digite uma mensagem…',
        RecentContent: 'Arquivos abertos na Biblioteca e suas atividades mais recentes ficarão visíveis aqui.',
        NoFavItems: 'NENHUM FAVORITO FOI ADICIONADO',
        FavContent: 'Sempre que você ver este ícone, clique nele! Tudo o que você adicionou em Favoritos será salvo aqui.',
        NoRecentItems: 'SEM ATIVIDADE RECENTE',
        ActivateTouchIDAlert: 'Deseja ativar o TouchID?',
        OK: 'OK',
        ExitApp: 'Sair',
        ThisSurveyWillEndOn: 'Esta pesquisa encerrará em',
        SearchInLib: 'Buscar en la Biblioteca',
        Done: 'Concluído',
        Clear: 'Apagar',
        Share: 'Compartilhar',
        Browser: 'Abrir no Navegador',
        BrowserIOS: 'Abrir no Safari',
        Print: 'Imprimir',
        InternetConnection: "Verifique sua conexão com a internet",
        NotSignInContent: 'Obtenha um conteúdo exclusivo e desfrute da facilidade no acesso  a todos os seus documentos favoritos.',
        WhySignIn: 'Por que acessar a ITA Connect?',
        YES: 'Sim',
        NO: 'Não',
        RememberAccountSettings: 'Lembrar as configurações da sua conta neste dispositivo?',
        ChangePassword: 'Alterar senha',
        ITATeam: 'ITA App Team',
        me: 'EU,',
        Gallary: 'GALERIA',
        Camera: 'CÂMERA',
        Close: 'FECHAR',
        ChooseImageFrom: 'Selecionar imagem…',
        NoMessageFound: 'Nenhuma mensagem foi encontrada para este ticket',
        SystemMessage: 'Sua mensagem foi enviada com sucesso. Entraremos em contato caso seja necessário uma resposta.',
        Send: 'Enviar',
        NotificationLanguage: 'Idioma de Notificações',
        TouchIdTradeMark: 'Touch ID é uma marca registrada da Apple Inc.',
        TouchIdTurnOff: 'Você pode desativar o Touch ID a qualquer momento.',
        TouchIdWarning: 'O uso do Touch ID não é recomendado caso o dispositivo não seja de um único usuário. Se o dispositivo for perdido, roubado ou compartilhado, os outros usuários poderão acessar as informações pessoais como contas com logins e senhas salvas. ',
        TouchIdMessage: 'Utilize o Touch ID para acessar a conta, sem ter que inserir a senha.',
        FaceIdTradeMark: 'Face ID é uma marca registrada da Apple Inc.',
        FaceIdTurnOff: 'Você pode desativar o Face ID a qualquer momento.',
        FaceIdWarning: 'O uso do Face ID não é recomendado caso o dispositivo não seja de um único usuário. Se o dispositivo for perdido, roubado ou compartilhado, os outros usuários poderão acessar as informações pessoais como contas com logins e senhas salvas. ',
        FaceIdMessage: 'Utilize o Face ID para acessar a conta, sem ter que inserir a senha.',
        GetStarted: 'Iniciar',
        Settings: 'Configuração',
        EnterClientName: 'Nome do cliente',
        WhoIsTheClient: 'Quem é o cliente?',
        YourRiskToleranceProfile: 'Perfil de Tolerância ao Risco',
        Bookmarked: 'Favoritos',
        Bookmark: 'Marcar como favorito',
        SeeAllVideos: 'Assista todos os vídeos',
        Password: "Senha",
        Discover: "Explorar",

        Filter: "Filtro",
        Flyer: "Folhetos",
        FundPlatform: "Plataforma de Fundos",
        Language: "Idioma",
        Notification: "Notificações",
        Products: "Produtos",
        Profile: "Perfil",
        ReportAnIssue: 'INFORMAR UM ERRO',
        SmallReportAnIssue: 'Informar um erro',
        RiskProfile: "Perfil de risco",
        Step: 'Passo',
        Security: "Segurança",
        SocialPosts: "Mídia Social",
        TouchID: "Touch ID®",
        Vidoes: "Vídeos",
        Library: "Biblioteca",
        Resource: "Recursos",
        Night_mode: 'Não perturbe',
        Getting_started: 'Introdução',
        //common
        PH_EMAIL: 'Inserir o seu e-mail',
        PH_NAME: 'Inserir o seu nome',
        PH_PASSWORD: 'Digitar a sua senha',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: 'Confirmar a senha',
        PH_FIRST_NAME: 'Inserir o seu nome',
        PH_LAST_NAME: 'Inserir o seu sobrenome',
        PH_INTRODUCER_CODE: 'Inserir o código do consultor',
        //common error
        ER_VALID_EMAIL: 'Fornecer um endereço de e-mail válido',
        ER_CURRENT_PASSWORD: 'Digite a senha atual',
        ER_NEW_PASSWORD: 'Digite a nova senha',
        ER_PASSWORD_MISMATCH: 'Essas senhas não coincidem',
        ER_CONFIRM_PASSWORD: 'Confirme a nova senha',
        ER_INTRODUCER_CODE: 'Inserir o código do consultor',
        ER_ENTER_EMAIL: 'Inserir o seu e-mail',
        ER_SELECTED_IMAGE: 'Selecionar foto',
        ER_ENTER_PASS: 'Inserir a sua senha',
        ER_ENTER_NAME: 'Inserir o seu nome',
        ER_CONFIRMATION_CODE: 'Inserir o seu código de confirmação',
        ER_ENTER_CONFIRM: 'Confirmar a sua senha',
        ER_PASS_NOT_MATCH: 'Senha não corresponde',
        //SignIn
        SignIn: "Entrar",
        Signup: "Inscreva-se",
        RememberMe: "Lembrar senha",
        ForgotPassword: "Esqueceu sua senha?",
        ContinueAsGuest: "Permanecer como convidado",
        Privacy: "Privacidade",
        Preferences: "Preferências",
        About: "Sobre",
        CopyRight: "© 2019 ITA Distribution. Todos os direitos reservados. Versão 1.0",
        //change password
        Current: "Atual",
        New: "Novo",
        Confirm: "Confirmar",
        Save: "Salvar",
        //EnterCode
        EnterConfirmationCode: "Inserir o código de confirmação",
        Enter6DigitCode: "Digitar o código de 6 dígitos que foi enviado para o seu e-mail xxx@xxxxxxxxx.com.",
        RequestNewOne: "Solicitar um novo código",
        ReturnToLogin: "Retornar para sessão inicial",

        //forgot password
        TroubleLogin: "Dificuldade com o login?",
        HelpUsToIdentify: "Ajude-nos a identificar a sua identidade.",
        //Language Options
        LanguageOptions: "Opções de idioma",
        ChineseTradition: "中文",
        ChineseSimplified: "简体中文",
        English: "English",
        Japanese: "日本語",
        Korean: "한국어",
        Portugese: "Português",
        Russian: "Русский",
        Spanish: "Español",
        //Notification
        PushNotification: "Notificações PUSH",
        NewsUpdate: "Notícias Atualizadas",
        LibraryUpdate: "Biblioteca Atualizada",
        //Profile
        Recent: "Recente",
        Favorite: "Favoritos",
        //Report an Issue
        ReportAnIssueConversationStart: "As conversas iniciadas neste aplicativo ficarão visíveis aqui",
        //Reset Password
        ResetPassword: "Inserir a nova senha",
        //Resources
        TakeTest: "FAÇA O TESTE",
        Search: "BUSCA",
        //Risk Profile
        Continue: "CONTINUAR",
        Calculate: "CALCULAR",
        //Settings
        SignOut: "Sair",
        SignOutWarning: "Deseja sair do aplicativo?",
        Cancel: "Cancelar",
        Yes: "Sim",
        FAQ: "Perguntas Frequentes (FAQ)",
        //Signup Password
        TermsAndConditions: "Termos & Condições",
        AgreeTerms: "Ao clicar " + '"Inscreva-se"' + " Eu concordo com o  ITA Distribution",

        //DiscoverList
        PrintedVersion: "PRINTED VERSION",
        DigitalOnly: "DIGITAL ONLY",
        PrintAndDigital: "PRINT AND DIGITAL",
        Submit: 'ENVIAR',
        Submited: "ENVIADO",
        //ProductList
        ViewAll: "Ver todos",
        //Getting Started
        Skip: "IGNORAR",
        WelcomeToITA: "Bem-vindo a ITA Connect",
        WelcomeToITADetail: "Um aplicativo para gerenciar seus negócios em qualquer lugar através do seu smartphone, com acesso às ferramentas para o sucesso.",
        DiscoverDetail: "As últimas novidades da empresa, promoções atuais e muito mais",
        LibraryDetail: "Acesso imediato aos recursos e materiais de marketing da Investors Trust",
        LibraryMore: "Arquive e compartilhe arquivos de forma ágil",
        ResourceDetail: "Determine o perfil de risco de seus clientes",
        ResourceMore: "Plataforma de Fundos interativos com recursos de pesquisa e filtro",
        ProfileDetail: "Encontre facilmente suas atividades recentes e documentos arquivados acessando rapidamente os recursos que você mais utiliza",
        CancelRiskProfileTest: "Deseja fechar a tela?",
        PasswordRules: "Por motivos de segurança, sugerimos que você crie uma senha forte que não tenha sido utilizada anteriormente. As diretrizes para uma senha forte incluem:\nPelo menos uma letra (maiúscula ou minúscula) \nPelo menos um numero \nPelo menos um caractere especial ! # $ % + / = @ ~",
        NotificationRules: "Ative as notificações da ITA Connect nas configurações do seu celular para manter-se atualizado com as últimas novidades do Mobile App Team da Investors Trust.",
        NO_DATA_FOUND: 'Nenhum dado foi encontrado',
        SEARCHINFUND: 'Busque por ISIN ou nome do fundo',
        FingerprintRequired: 'Impressão digital',
        TouchSensor: 'Sensor de impressão digital',
    },
    "es": {
        Vote: 'VOTAR',
        Voted: 'VOTADO',
        AssetClass: "Clase de Activo",
        InvestmentUniverse: "Universo de Inversión",
        FundFamily: "Familia de Fondos",
        ExitAppMessage: '¿Cerrar la aplicación?',
        Version: 'Versión:',
        financial: 'Not a Financial Adviser ?',
        financiallogin:'Financial Adviser Log In:',
        NOFAV: 'AÚN NO SE HAN AGREGADO FAVORITOS',
        NOFAVDES: 'Haga clic en este ícono para guardar sus Favoritos',
        RiskProfileResult: 'Basado en sus respuestas, usted tiene un perfil de Tolerancia al Riesgo XXXXXX. A continuación, podrá ver un ejemplo de un portafolio de inversión en USD, siguiendo una estrategia XXXXXX.',
        TypeMessage: 'Escriba un mensaje…',
        RecentContent: 'Los archivos abiertos en la Biblioteca y su actividad más reciente se mostrarán aquí.',
        NoFavItems: 'AÚN NO SE HAN AGREGADO FAVORITOS',
        FavContent: 'Haga clic en este ícono para guardar sus Favoritos',
        NoRecentItems: 'NO HAY ACTIVIDAD RECIENTE',
        ActivateTouchIDAlert: '¿Desea activar Touch ID?',
        OK: 'OK',
        ExitApp: 'Salir',
        ThisSurveyWillEndOn: 'Esta encuesta finalizará el',
        SearchInLib: 'Buscar en la Biblioteca',
        Done: 'Terminado',
        Clear: 'Borrar',
        Share: 'Compartir',
        Browser: 'Open in Browser',
        BrowserIOS: 'Open in Safari',
        Print: 'Imprimir',
        InternetConnection: "Chequee su conexión a internet",
        NotSignInContent: 'Acceda a un contenido exclusivo y disfrute de un rápido acceso a sus documentos favoritos.',
        WhySignIn: '¿Por qué ingresar a ITA Connect?',
        YES: 'SÍ',
        NO: 'No',
        RememberAccountSettings: '¿Recuerda la configuración de su cuenta en este dispositivo?',
        ChangePassword: 'Cambiar la contraseña',
        ITATeam: 'ITA App Team',
        me: 'YO,',
        Gallary: 'GALERÍA',
        Camera: 'CÁMARA',
        Close: 'CERRAR',
        ChooseImageFrom: 'Elija la imagen desde',
        NoMessageFound: 'No se encontraron mensajes para este ticket.',
        SystemMessage: 'Su mensaje ha sido enviado. Lo estaremos contactando si fuera necesaria una respuesta.',
        Send: 'Enviar',
        NotificationLanguage: 'Idioma de notificación',
        TouchIdTradeMark: 'Touch ID es una marca registrada de Apple Inc. ',
        TouchIdTurnOff: 'Touch ID se puede desactivar en cualquier momento.',
        TouchIdWarning: 'No se recomienda el uso de Touch ID si usted no es el único usuario de este dispositivo. Recuerde que si extravía su dispositivo o lo comparte, otros usuarios podrán acceder a sus datos personales guardados en el dispositivo. ',
        TouchIdMessage: 'Use Touch ID para iniciar sesión, sin tener que ingresar su contraseña.',
        FaceIdTradeMark: 'Face ID es una marca registrada de Apple Inc. ',
        FaceIdTurnOff: 'Face ID se puede desactivar en cualquier momento.',
        FacedWarning: 'No se recomienda el uso de Face ID si usted no es el único usuario de este dispositivo. Recuerde que si extravía su dispositivo o lo comparte, otros usuarios podrán acceder a sus datos personales guardados en el dispositivo. ',
        FaceIdMessage: 'Use Face ID para iniciar sesión, sin tener que ingresar su contraseña.',
        GetStarted: 'Para comenzar',
        Settings: 'Configuración',
        EnterClientName: 'Nombre del cliente',
        WhoIsTheClient: '¿Quién es el cliente?',
        YourRiskToleranceProfile: 'Perfil de Tolerancia al Riesgo',
        Bookmarked: 'Favorito',
        Bookmark: 'Agregar a Favoritos ',
        SeeAllVideos: 'Ver todos los videos',
        Password: "Contraseña",
        Discover: "Explorar",

        Filter: "Filtrar",
        Flyer: "Folletos",
        FundPlatform: "Plataforma de Fondos",
        Language: "Idioma",
        Notification: "Notificaciones",
        Products: "Productos",
        Profile: "Perfil",
        ReportAnIssue: 'REPORTAR UN PROBLEMA',
        SmallReportAnIssue: 'Reportar un problema',
        RiskProfile: "Perfil de Riesgo",
        Step: 'Paso',
        Security: "Seguridad",
        SocialPosts: "Contenido a compartir",
        TouchID: "Touch ID®",
        Vidoes: "Videos",
        Library: "Biblioteca",
        Resource: "Recursos",
        Night_mode: 'No Molestar',
        Getting_started: 'Introducción',
        //common
        PH_EMAIL: 'Ingresar email',
        PH_NAME: 'Ingresar nombre',
        PH_PASSWORD: 'Ingresar contraseña',
        PH_NEW_PASSWORD: "New your Password",
        PH_CONFIRM_PASSWORD: 'Confirmar contraseña',
        PH_FIRST_NAME: 'Ingresar primer nombre',
        PH_LAST_NAME: 'Ingresar apellido',
        PH_INTRODUCER_CODE: 'Ingresar código de Introductor',
        //common error
        ER_VALID_EMAIL: 'Ingresar una dirección de email válida',
        ER_CURRENT_PASSWORD: 'Ingrese su actual contraseña',
        ER_NEW_PASSWORD: 'Ingrese su nueva contraseña',
        ER_PASSWORD_MISMATCH: 'Su nueva contraseña y la confirmación de contraseña no coinciden',
        ER_CONFIRM_PASSWORD: 'Confirme su nueva contraseña',
        ER_INTRODUCER_CODE: 'Ingresar código de Introductor',
        ER_ENTER_EMAIL: 'Ingresar dirección de email',
        ER_SELECTED_IMAGE: 'Seleccionar foto',
        ER_ENTER_PASS: 'Ingresar contraseña',
        ER_ENTER_NAME: 'Ingresar nombre',
        ER_CONFIRMATION_CODE: 'Ingresar código de confirmación',
        ER_ENTER_CONFIRM: 'Confirmar contraseña',
        ER_PASS_NOT_MATCH: 'La contraseña no coincide',
        //SignIn
        SignIn: "Iniciar sesión",
        Signup: "Crear cuenta",
        RememberMe: "Recordarme",
        ForgotPassword: "¿Olvidó su contraseña?",
        ContinueAsGuest: "Continuar como invitado",
        Privacy: "Privacidad",
        Preferences: "Preferencias",
        About: "Sobre",
        CopyRight: "© 2019 ITA Distribution. Todos los derechos reservados. Versión 1.0",
        //change password
        Current: "Actual",
        New: "Nueva",
        Confirm: "Confirmar",
        Save: "Guardar",
        //EnterCode
        EnterConfirmationCode: "Ingresar el código de confirmación",
        Enter6DigitCode: "Ingresar el código de 6 dígitos que enviamos a xxx@xxxxxx.com",
        RequestNewOne: "Solicitar nuevo código",
        ReturnToLogin: "Volver a Iniciar sesión",

        //forgot password
        TroubleLogin: "¿Problemas para acceder?",
        HelpUsToIdentify: "Ayúdenos a identificar su identidad",
        //Language Options
        LanguageOptions: "Opciones de Idioma",
        ChineseTradition: "中文",
        ChineseSimplified: "简体中文",
        English: "English",
        Japanese: "日本語",
        Korean: "한국어",
        Portugese: "Português",
        Russian: "Русский",
        Spanish: "Español",
        //Notification
        PushNotification: "Notificaciones PUSH",
        NewsUpdate: "Actualizar noticias",
        LibraryUpdate: "Actualizar Biblioteca",
        //Profile
        Recent: "Reciente",
        Favorite: "Favorito",
        //Report an Issue
        ReportAnIssueConversationStart: "Las conversaciones iniciadas en esta app se mostrarán aquí",
        //Reset Password
        ResetPassword: "Ingresar nueva contraseña",
        //Resources
        TakeTest: "DETERMINAR PERFIL DE RIESGO",
        Search: "BUSCAR",
        //Risk Profile
        Continue: "CONTINUAR",
        Calculate: "CALCULAR",
        //Settings
        SignOut: "Cerrar sesión",
        SignOutWarning: "¿Está seguro de cerrar esta pantalla?",
        Cancel: "Cancelar",
        Yes: "SÍ",
        FAQ: "Preguntas Frecuentes",
        //Signup Password
        TermsAndConditions: "Términos y Condiciones",
        AgreeTerms: "Al hacer clic en " + '"Iniciar sesión"' + " Declaro que estoy de acuerdo con los …...........del ITA Distribution",

        //DiscoverList
        PrintedVersion: "PRINTED VERSION",
        DigitalOnly: "DIGITAL ONLY",
        PrintAndDigital: "PRINT AND DIGITAL",
        Submit: 'ENVIAR',
        Submited: "ENVIADO",
        //ProductList
        ViewAll: "Ver todos",
        //Getting Started
        Skip: "OMITIR",
        WelcomeToITA: "Bienvenido a ITA Connect",
        WelcomeToITADetail: "Una aplicación para gestionar sus negocios desde su teléfono móvil, accediendo a las herramientas más innovadoras de la compañía",
        DiscoverDetail: "Las últimas novedades de la compañía, promociones actuales, encuestas en vivo y mucho más",
        LibraryDetail: "Acceso inmediato a los recursos de Investors Trust y  materiales de marketing",
        LibraryMore: "Archive y comparta archivos de forma ágil",
        ResourceDetail: "Determine el perfil de riesgo de sus clientes ",
        ResourceMore: "Acceda a una plataforma de fondos interactiva con herramientas de búsqueda",
        ProfileDetail: "Encuentre fácilmente su Actividad Reciente y los documentos archivados para un rápido acceso a sus recursos",
        CancelRiskProfileTest: "¿Está seguro de cerrar esta pantalla?",
        PasswordRules: "Le sugerimos crear una contraseña segura que no haya usado antes. La contraseña debe cumplir con los siguientes requisitos:\nIncluir al menos una letra (mayúscula o minúscula)\nIncluir al menos un número\nIncluir al menos un caracter especial  (! # $ % +       / = @ ~.)",
        NotificationRules: "Habilite las notificaciones de ITA Connect en la sección de Configuración de su dispositivo y manténgase al día con las novedades del Mobile App Team de Investors Trust.",
        NO_DATA_FOUND: 'No se encontraron datos',
        SEARCHINFUND: 'Buscar por ISIN o Nombre del fondo',
        FingerprintRequired: 'Huella digital requerida',
        TouchSensor: 'Sensor táctil',
    }
});
export default language;
