export const RISK_PROFILE_QUESTION_REQUEST = 'RISK_PROFILE_QUESTION_REQUEST';
export const RISK_PROFILE_QUESTION_SUCCESS = 'RISK_PROFILE_QUESTION_SUCCESS';
export const RISK_PROFILE_QUESTION_FAILURE = 'RISK_PROFILE_QUESTION_FAILURE';
// Risk Profile Detail
export const RISK_PROFILE_DETAILS_REQUEST = 'RISK_PROFILE_DETAILS_REQUEST';
export const RISK_PROFILE_DETAILS_SUCCESS = 'RISK_PROFILE_DETAILS_SUCCESS';
export const RISK_PROFILE_DETAILS_FAILURE = 'RISK_PROFILE_DETAILS_FAILURE';
export const RISK_PROFILE_RESOURCE_ID = 'RISK_PROFILE_RESOURCE_ID';
